Assignment -6
Sneha1251/backend_training pull request #6
Opened 2024-05-06 05:23 UTC by Sneha1251

2024-05-07 10:40 UTC, DevGarima requested changes

2024-05-07 10:40 UTC, DevGarima commented on src/assignment-6/src/middlewares/errorHandler.ts
> +  err: Error,
Error is not defined anywhere.

2024-05-09 15:57 UTC, Sneha1251 commented on src/assignment-6/src/middlewares/errorHandler.ts
> +  err: Error,
done

2024-05-10 08:26 UTC, DevGarima approved these changes

2024-05-10 08:26 UTC, merged